name=input("enter the name of the user:")
branch=input("enter the branch of the user:")
gender=input("enter the gender of the user:")
college=input("enter the college of the user:")
age=int(input("enter the age of the user:"))
print("name:",name)
print("branch:",branch)
print("gender:",gender)
print("college",college)
print("age:",age)
